### ISSUE TITLE
"loads the rules as new tests" fails with "TypeError: Cannot call method 'addTest' of undefined"

### ISSUE THREAD

**Issue by mmai** [DamonOehlman/testrest#5]
testrest tests don't pass on my machine :

``` sh
npm install testrest
cd node_modules/testrest
npm install
mocha --reporter spec test/main.js
```

Gives an error at "loads the rules as new tests" with the following trace : 

```
mocha --reporter spec test/main.js
[Error: Cannot find module './DTraceProviderBindings']


  testREST functionalit tests
    GET tests
      ✓ can load the definition file: get.txt 
      ✓ can parse the definition file 
      ◦ loads the rules as new tests: {}
      1) loads the rules as new tests
    PUT tests
      ✓ can load the definition file: put.txt 
      ✓ can parse the definition file 
      ◦ loads the rules as new tests: {}
      2) loads the rules as new tests


  ✖ 2 of 6 tests failed:

  1) testREST functionalit tests GET tests loads the rules as new tests:
     TypeError: Cannot call method 'addTest' of undefined
      at /home/henri/travaux/puzzlebobble_manager/rank_manager/node_modules/testrest/lib/testrest.js:57:27
      at Array.forEach (native)
      at Context.<anonymous> (/home/henri/travaux/puzzlebobble_manager/rank_manager/node_modules/testrest/lib/testrest.js:56:19)
      at Test.run (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runnable.js:158:32)
      at Runner.runTest (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:270:10)
      at /home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:314:12
      at next (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:198:14)
      at /home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:207:7
      at next (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:157:23)
      at Array.0 (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:175:5)
      at EventEmitter._tickCallback (node.js:192:40)

  2) testREST functionalit tests PUT tests loads the rules as new tests:
     TypeError: Cannot call method 'addTest' of undefined
      at /home/henri/travaux/puzzlebobble_manager/rank_manager/node_modules/testrest/lib/testrest.js:57:27
      at Array.forEach (native)
      at Context.<anonymous> (/home/henri/travaux/puzzlebobble_manager/rank_manager/node_modules/testrest/lib/testrest.js:56:19)
      at Test.run (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runnable.js:158:32)
      at Runner.runTest (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:270:10)
      at /home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:314:12
      at next (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:198:14)
      at /home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:207:7
      at next (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:157:23)
      at Array.0 (/home/henri/.nvm/v0.6.14/lib/node_modules/mocha/lib/runner.js:175:5)
      at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by DamonOehlman** [comment]
I just pushed an update to deal with newer versions of mocha.  Tests run on my machine let me know if they pass on yours...

**Comment by mmai** [comment]
They pass. Thank you very much !
